import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area } from 'recharts';
import { Target, CheckCircle2, TrendingUp, Cpu, Award, Download, RotateCcw, ChevronDown, ChevronUp, Network, Zap } from 'lucide-react';

const dummyData = [
  { month: 'Jan', actual: 400, predicted: 420 },
  { month: 'Feb', actual: 300, predicted: 310 },
  { month: 'Mar', actual: 550, predicted: 540 },
  { month: 'Apr', actual: 200, predicted: 210 },
  { month: 'May', actual: 278, predicted: 280 },
  { month: 'Jun', actual: 189, predicted: 195 },
  { month: 'Jul', actual: 239, predicted: 245 },
];

const convergenceData = Array.from({ length: 20 }, (_, i) => ({
  generation: i * 5,
  fitness: Math.max(0, 95 - (80 * Math.exp(-i * 0.25)) + (Math.random() * 2 - 1)),
  poa_only: Math.max(0, 85 - (70 * Math.exp(-i * 0.15)) + (Math.random() * 3 - 1))
}));

const ALL_FEATURES = ['Temperature', 'Humidity', 'Rainfall', 'Wind Speed', 'Atmospheric Pressure', 'Solar Radiation', 'Soil Moisture'];

export default function Output() {
  const navigate = useNavigate();
  const [accuracy, setAccuracy] = useState(0);
  const [targetAccuracy, setTargetAccuracy] = useState(0);
  const [selectedFeatures, setSelectedFeatures] = useState([]);
  const [isAccordionOpen, setIsAccordionOpen] = useState(false);

  useEffect(() => {
    // Generate random target accuracy between 85 and 98
    const target = (Math.random() * (98 - 85) + 85).toFixed(1);
    setTargetAccuracy(parseFloat(target));

    // Select 3 to 4 random features from the main 4 plus some others
    const coreFeatures = ['Temperature', 'Humidity', 'Rainfall', 'Wind Speed'];
    const shuffled = [...coreFeatures].sort(() => 0.5 - Math.random());
    const count = Math.floor(Math.random() * 2) + 3; // 3 or 4
    setSelectedFeatures(shuffled.slice(0, count));
  }, []);

  useEffect(() => {
    // Animate counter
    if (accuracy < targetAccuracy) {
      const timer = setTimeout(() => {
        setAccuracy(prev => {
          const next = prev + 1.5;
          return next > targetAccuracy ? targetAccuracy : next;
        });
      }, 30);
      return () => clearTimeout(timer);
    }
  }, [accuracy, targetAccuracy]);

  const handleDownload = () => {
    // Fake download interaction
    const element = document.createElement("a");
    const file = new Blob(["Simulated Report generated by POA Climate App"], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "poa-ga-report.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const featureImportance = selectedFeatures.map((f, i) => ({
    name: f,
    value: 85 - (i * 12) + Math.floor(Math.random() * 5)
  }));

  return (
    <div className="py-8">
      {/* Header Section */}
      <motion.div 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-col md:flex-row items-start md:items-center justify-between mb-8 gap-4"
      >
        <div>
          <h2 className="text-3xl font-bold mb-2">Analysis Results</h2>
          <p className="text-gray-400">Model execution complete.</p>
        </div>
        <div className="flex flex-col sm:flex-row items-center gap-3">
          <div className="px-4 py-2 rounded-lg bg-gradient-to-r from-indigo-500/20 to-purple-500/20 border border-indigo-500/30 flex items-center gap-2 shadow-lg shadow-indigo-500/10">
            <Award className="w-5 h-5 text-indigo-400" />
            <span className="font-semibold text-indigo-100">Optimized using POA + GA</span>
          </div>
          <div className="flex gap-2 w-full sm:w-auto">
            <button 
              onClick={handleDownload}
              className="flex-1 sm:flex-none px-4 py-2 bg-white/10 hover:bg-white/20 border border-white/10 rounded-lg text-sm font-medium flex items-center justify-center gap-2 transition-colors"
            >
              <Download className="w-4 h-4" />
              Report
            </button>
            <button 
              onClick={() => navigate('/input')}
              className="flex-1 sm:flex-none px-4 py-2 bg-indigo-600 hover:bg-indigo-500 rounded-lg text-sm font-medium flex items-center justify-center gap-2 transition-colors shadow-lg shadow-indigo-500/20"
            >
              <RotateCcw className="w-4 h-4" />
              Run Again
            </button>
          </div>
        </div>
      </motion.div>

      {/* KPI Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.1 }}
          className="glass-panel p-6 flex items-center gap-4 relative overflow-hidden"
        >
          <div className="absolute -right-4 -top-4 w-24 h-24 bg-green-500/10 rounded-full blur-2xl"></div>
          <div className="w-12 h-12 rounded-xl flex items-center justify-center bg-green-500/10 z-10">
            <Target className="w-6 h-6 text-green-400" />
          </div>
          <div className="z-10">
            <p className="text-sm text-gray-400 font-medium">Model Accuracy</p>
            <p className="text-3xl font-bold mt-1 text-green-400">
              {accuracy.toFixed(1)}%
            </p>
          </div>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.2 }}
          className="glass-panel p-6 flex items-center gap-4"
        >
          <div className="w-12 h-12 rounded-xl flex items-center justify-center bg-blue-500/10">
            <CheckCircle2 className="w-6 h-6 text-blue-400" />
          </div>
          <div>
            <p className="text-sm text-gray-400 font-medium">Features Selected</p>
            <p className="text-2xl font-bold mt-1">{selectedFeatures.length} / 7</p>
          </div>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.3 }}
          className="glass-panel p-6 flex items-center gap-4"
        >
          <div className="w-12 h-12 rounded-xl flex items-center justify-center bg-purple-500/10">
            <TrendingUp className="w-6 h-6 text-purple-400" />
          </div>
          <div>
            <p className="text-sm text-gray-400 font-medium">Loss Reduction</p>
            <p className="text-2xl font-bold mt-1">45.2%</p>
          </div>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.4 }}
          className="glass-panel p-6 flex items-center gap-4"
        >
          <div className="w-12 h-12 rounded-xl flex items-center justify-center bg-indigo-500/10">
            <Cpu className="w-6 h-6 text-indigo-400" />
          </div>
          <div>
            <p className="text-sm text-gray-400 font-medium">Convergence Time</p>
            <p className="text-2xl font-bold mt-1">124ms</p>
          </div>
        </motion.div>
      </div>

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="glass-panel p-6 flex flex-col"
        >
          <div className="mb-6">
            <h3 className="text-lg font-semibold">Optimization Convergence (POA + GA)</h3>
            <p className="text-sm text-gray-400">Fitness score improvement over generations compared to baseline.</p>
          </div>
          <div className="h-72 w-full flex-1">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={convergenceData} margin={{ top: 5, right: 20, left: -20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#374151" />
                <XAxis dataKey="generation" stroke="#6B7280" tick={{fill: '#9CA3AF', fontSize: 12}} tickLine={false} axisLine={false} />
                <YAxis stroke="#6B7280" tick={{fill: '#9CA3AF', fontSize: 12}} tickLine={false} axisLine={false} />
                <Tooltip 
                  contentStyle={{ backgroundColor: 'rgba(17, 24, 39, 0.9)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', backdropFilter: 'blur(8px)' }}
                  itemStyle={{ fontSize: '14px', fontWeight: 500 }}
                />
                <Line type="monotone" name="POA + GA Hybrid" dataKey="fitness" stroke="#9333EA" strokeWidth={3} dot={false} activeDot={{ r: 6, fill: '#9333EA', stroke: '#fff' }} />
                <Line type="monotone" name="POA Only" dataKey="poa_only" stroke="#6B7280" strokeWidth={2} strokeDasharray="5 5" dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
          className="glass-panel p-6 flex flex-col"
        >
          <div className="mb-6">
            <h3 className="text-lg font-semibold">Feature Importance Selection</h3>
            <p className="text-sm text-gray-400">Attributes selected by the GA for the final model.</p>
          </div>
          <div className="h-72 w-full flex-1">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={featureImportance} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#374151" />
                <XAxis type="number" stroke="#6B7280" tick={{fill: '#9CA3AF', fontSize: 12}} axisLine={false} tickLine={false} />
                <YAxis dataKey="name" type="category" stroke="#6B7280" tick={{fill: '#E5E7EB', fontSize: 12}} width={90} axisLine={false} tickLine={false} />
                <Tooltip 
                  cursor={{fill: 'rgba(255,255,255,0.05)'}}
                  contentStyle={{ backgroundColor: 'rgba(17, 24, 39, 0.9)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', backdropFilter: 'blur(8px)' }}
                />
                <Bar dataKey="value" fill="#4F46E5" radius={[0, 4, 4, 0]}>
                  {featureImportance.map((entry, index) => (
                    <cell key={`cell-${index}`} fill={index === 0 ? '#4F46E5' : '#6366f1'} opacity={1 - (index * 0.15)} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </motion.div>
      </div>

      {/* Accordion / How it Works */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.7 }}
        className="glass-panel overflow-hidden border border-white/10"
      >
        <button 
          onClick={() => setIsAccordionOpen(!isAccordionOpen)}
          className="w-full px-6 py-5 flex items-center justify-between bg-white/5 hover:bg-white/10 transition-colors"
        >
          <div className="flex items-center gap-3">
            <div className="p-2 bg-indigo-500/20 rounded-lg text-indigo-400">
              <Network className="w-5 h-5" />
            </div>
            <h3 className="text-lg font-semibold text-white text-left">How the Model Works</h3>
          </div>
          <div className={`p-1 rounded-full bg-white/10 text-gray-300 transition-transform duration-300 ${isAccordionOpen ? 'rotate-180' : ''}`}>
            <ChevronDown className="w-5 h-5" />
          </div>
        </button>
        
        <AnimatePresence>
          {isAccordionOpen && (
            <motion.div 
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3 }}
              className="border-t border-white/10"
            >
              <div className="p-6 md:p-8 bg-black/20 text-gray-300 space-y-6">
                <p className="leading-relaxed text-sm md:text-base">
                  This application utilizes a powerful hybrid approach combining the <strong>Perfumer Optimization Algorithm (POA)</strong> and <strong>Genetic Algorithms (GA)</strong> to optimize climate pattern recognition models.
                </p>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-3">
                    <h4 className="flex items-center gap-2 font-medium text-indigo-300">
                      <Zap className="w-4 h-4" /> Phase 1: POA Exploration
                    </h4>
                    <ul className="space-y-2 text-sm pl-6 list-disc marker:text-indigo-500/50">
                      <li>POA effectively explores the vast, multi-dimensional solution space of climate parameters.</li>
                      <li>It rapidly identifies promising regions mimicking how scent diffuses and settles in environments.</li>
                      <li>Prevents premature convergence which is common in standalone neural networks.</li>
                    </ul>
                  </div>
                  
                  <div className="space-y-3">
                    <h4 className="flex items-center gap-2 font-medium text-purple-300">
                      <Network className="w-4 h-4" /> Phase 2: GA Refinement
                    </h4>
                    <ul className="space-y-2 text-sm pl-6 list-disc marker:text-purple-500/50">
                      <li>Takes the promising solutions found by POA and refines them using evolutionary principles.</li>
                      <li>Applies <em>Selection</em>, <em>Crossover</em>, and <em>Mutation</em> to breed optimal feature weights.</li>
                      <li>The hybrid approach yields the highest possible accuracy while reducing computational overhead.</li>
                    </ul>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </div>
  );
}
